image: docker:stable

services:
  - docker:dind

variables:
  DOCKER_IMAGE_NAME: registry.gitlab.com/aranofacundo/knarr
  DOCKER_IMAGE_TAG: $DOCKER_IMAGE_NAME:$CI_COMMIT_TAG
  DOCKER_IMAGE_LATEST: $DOCKER_IMAGE_NAME:latest

stages:
  - build
  - release

before_script:
  - docker info

build:
  stage: build
  before_script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  script:
    - docker build -t $DOCKER_IMAGE_TAG .
    - docker push $DOCKER_IMAGE_TAG
  after_script:
    - docker logout $CI_REGISTRY
  only:
    - tags
  tags:
    - docker

release:
  stage: release
  before_script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  script:
    - docker pull $DOCKER_IMAGE_TAG
    - docker tag $DOCKER_IMAGE_TAG $DOCKER_IMAGE_LATEST
    - docker push $DOCKER_IMAGE_LATEST
  after_script:
    - docker logout $CI_REGISTRY
  only:
    - tags
  tags:
    - docker
