image: docker:19

services:
  - docker:19-dind

variables:
  DOCKER_DRIVER: overlay2
  DI_TAG_STABLE: $CI_REGISTRY_IMAGE:stable
  DI_TAG_LATEST: $CI_REGISTRY_IMAGE:latest

stages:
  - build

before_script:
  - docker info

build_master:
  stage: build
  variables:
    DI_TAG_BUILD: $CI_REGISTRY_IMAGE:master-$CI_COMMIT_SHORT_SHA
  before_script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  script:
    - docker pull $DI_TAG_LATEST || true
    # Compila la imagen docker con sus etiquetas
    - docker build --cache-from $DI_TAG_LATEST --tag $DI_TAG_BUILD --tag $DI_TAG_LATEST .
    - docker push $DI_TAG_BUILD
    - docker push $DI_TAG_LATEST
  after_script:
    - docker logout $CI_REGISTRY
  only:
    - master
  tags:
    - docker

build_stable:
  stage: build
  variables:
    DI_TAG_BUILD: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  before_script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  script:
    - docker pull $DI_TAG_LATEST || true
    # Compila la imagen docker con sus etiquetas
    - docker build --cache-from $DI_TAG_LATEST --tag $DI_TAG_BUILD --tag $DI_TAG_STABLE .
    - docker push $DI_TAG_BUILD
    - docker push $DI_TAG_STABLE
  after_script:
    - docker logout $CI_REGISTRY
  only:
    - tags
  tags:
    - docker
